### ISSUE TITLE
每次投完票后，再点击菜单上，页面会抖动2下，才会拉取信息

### ISSUE THREAD

**Issue by chenhengjie123** [testerhome/testerhome#20]
每次投完票后，再点击菜单上，页面会抖动2下，才会拉取信息
![](https://testerhome.com/photo/2016/14091b80e5b723c6e6fa0c5f95ce2cb7.gif)

原链接：https://testerhome.com/topics/3923#reply7

**Comment by DoctorQ** [comment]
![95a4905c-9fb3-4239-ac46-de514acbd45d](https://cloud.githubusercontent.com/assets/4489853/12113695/7367a6ae-b3df-11e5-9ff7-6eb898221a95.png)

**Comment by lihuazhang** [comment]
没人用投票。。
