### ISSUE TITLE
由管理员修改过的内容，添加管理员修改标示。 

### ISSUE THREAD

**Issue by lihuazhang** [testerhome/testerhome#30]
由管理员修改过的内容，添加管理员修改标示。

**Comment by chenhengjie123** [comment]
想确认几点：

1. 管理员自己发的帖子然后自己去修改，是否应该不需要管理员修改标示？
2. 标示是直接显示在帖子内容，还是只需要显示在后台？
3. 是否需要显示操作的管理员 id ？

**Comment by lihuazhang** [comment]
管理员自己发的帖子然后自己去修改，是否应该不需要管理员修改标示？—— 显示就都显示吧。管理员也有很多个。
标示是直接显示在帖子内容，还是只需要显示在后台？——帖子内容都显示。
是否需要显示操作的管理员 id ？—— 需要

**Comment by chenhengjie123** [comment]
#
