### ISSUE TITLE
已结贴动作

### ISSUE THREAD

**Issue by lihuazhang** [testerhome/testerhome#34]
添加一个 已结贴 操作。 有些帖子，不用再回复或者不想被回复了。 就结贴。

**Comment by chenhengjie123** [comment]
想确认下：

结贴操作是否帖主和管理员都能操作？取消结贴呢？

**Comment by lihuazhang** [comment]
https://github.com/testerhome/testerhome/commit/3d562015248cb27a6387c6fdbecf9a0cc669f2cf

**Comment by chenhengjie123** [comment]
👍 我也刚写完。你的实现比我的更优，看来我还有很多东西要学。

有一个小建议，`app/controllers/replies_controller.rb` 里面的 `create` 方法应该也需要对已结帖时的创建回复做相应处理吧。否则通过模拟请求实际上还是可以回帖的。
